# -*- coding: utf-8 -*-
"""data_exploration01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JY-ASBQWBohaEKjDocf_VSxKwnMkVwS0
"""

from google.colab import drive

drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/data_science_project/Trips_full_Data.csv")

# to load the dataset we do
df = pd.read_csv("/content/drive/MyDrive/data_science_project/Trips_by_Distance.csv")

# now we ensure the date is parsed
df['Date'] = pd.to_datetime(df['Date'])

weekly_home = df.groupby('Week')['Population Staying at Home'].sum()
weekly_not_home = df.groupby('Week')['Population Not Staying at Home'].sum()
#to calculate the total of the population staying at home weekly

# now this is the distance band, that is the different distance ranges
distance_cols = [
    'Number of Trips <1', 'Number of Trips 1-3', 'Number of Trips 3-5',
    'Number of Trips 5-10', 'Number of Trips 10-25', 'Number of Trips 25-50',
    'Number of Trips 50-100', 'Number of Trips 100-250',
    'Number of Trips 250-500', 'Number of Trips >=500'
]

weekly_distance = df.groupby('Week')[distance_cols].sum()

