# -*- coding: utf-8 -*-
"""data_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1df9tDH8G4sDHNzbyC1ft9I5SzLg6bXNW
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/data_science_project/Trips_by_Distance.csv")
df['Date'] = pd.to_datetime(df['Date'])

distance_cols = [
    'Number of Trips <1', 'Number of Trips 1-3', 'Number of Trips 3-5',
    'Number of Trips 5-10', 'Number of Trips 10-25', 'Number of Trips 25-50',
    'Number of Trips 50-100', 'Number of Trips 100-250',
    'Number of Trips 250-500', 'Number of Trips >=500'
]
#these are the distance band columns

#now we group the weekly distance
weekly_distance = df.groupby('Week')[distance_cols].sum()

#now using scatterplot diagrams, wewe will compare different distance bands

plt.figure(figsize=(8,6))
plt.scatter(weekly_distance['Number of Trips 10-25'],
            weekly_distance['Number of Trips 50-100'],
            alpha=0.7)

plt.title("Trips 10–25 Miles vs 50–100 Miles")
plt.xlabel("Trips 10–25 Miles")
plt.ylabel("Trips 50–100 Miles")
plt.grid(True)

plt.savefig("10-25_vs_50-100.png", dpi=300)
plt.show()

#now for scatter plot 2, comparing less than a mile and 1-3 miles

plt.figure(figsize=(8,6))
plt.scatter(weekly_distance['Number of Trips <1'],
            weekly_distance['Number of Trips 1-3'],
            alpha=0.7, color='orange')

plt.title("Trips <1 Mile vs 1–3 Miles")
plt.xlabel("Trips <1 Mile")
plt.ylabel("Trips 1–3 Miles")
plt.grid(True)

plt.savefig("less-than1_vs_1-3.png", dpi=300)
plt.show()

#and finally the last scatterplot, comparing the 3-5 and 5-10 mile distance bands

plt.figure(figsize=(8,6))
plt.scatter(weekly_distance['Number of Trips 3-5'],
            weekly_distance['Number of Trips 5-10'],
            alpha=0.7, color='green')

plt.title("Trips 3–5 Miles vs 5–10 Miles")
plt.xlabel("Trips 3–5 Miles")
plt.ylabel("Trips 5–10 Miles")
plt.grid(True)
#to save the figure in our folder
plt.savefig("3-5_vs_5-10.png", dpi=300)
plt.show()

