# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vYhaY6G99onxGng7q1gZQ_GNLQbB_5_s
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

#now we need to reference our dataset from the coursework

df = pd.read_csv("/content/drive/MyDrive/data_science_project/Trips_by_Distance.csv")

df['Date'] = pd.to_datetime(df['Date'])

#now the weekly aggregate
distance_cols = [
    'Number of Trips <1', 'Number of Trips 1-3', 'Number of Trips 3-5',
    'Number of Trips 5-10', 'Number of Trips 10-25', 'Number of Trips 25-50',
    'Number of Trips 50-100', 'Number of Trips 100-250',
    'Number of Trips 250-500', 'Number of Trips >=500'
]

weekly_distance = df.groupby('Week')[distance_cols].sum()

#using one distance band, we will try to predict the other
X = weekly_distance.drop(columns=['Number of Trips 50-100'])
y = weekly_distance['Number of Trips 50-100']

#training and testing the model
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)
#for our predictions
y_pred = model.predict(X_test)

#calculaating the model performance metrics, and the weekly trip prediction
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

metrics = pd.DataFrame({
    'MAE': [mae],
    'RMSE': [rmse],
    'R2 Score': [r2]
})

metrics.to_csv("/content/drive/MyDrive/data_science_project/model_metrics.csv", index=False)
metrics

#predicted vs actual plot
plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred, alpha=0.7)
plt.xlabel("Actual Trips 50–100 Miles")
plt.ylabel("Predicted Trips 50–100 Miles")
plt.title("Predicted vs Actual Values")
plt.grid(True)
#now we print the graph
plt.savefig("predicted_vs_actual.png", dpi=300)
plt.show()

residuals = y_test - y_pred
#residual plot used to visualise prediction errors against predicted values
plt.figure(figsize=(8,6))
plt.scatter(y_pred, residuals, alpha=0.7)
plt.axhline(0, color='red', linestyle='--')
plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")
plt.grid(True)

plt.savefig("residual_plot.png", dpi=300)
plt.show()

