# -*- coding: utf-8 -*-
"""parallel_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WJW_NjnNn1znTklxOSRy5hf3W1Ll9pF
"""

from google.colab import drive
drive.mount('/content/drive')

#the comparison between sequential and parallel processing performance

import pandas as pd
import numpy as np
import time
from multiprocessing import Pool, cpu_count
import matplotlib.pyplot as plt

#now that we have imported all of our libraries we load our dataset from the drive
df = pd.read_csv("/content/drive/MyDrive/data_science_project/Trips_by_Distance.csv")

#we need a fuction that takes a significant amount of time for cpu-bound work
def heavy_computation(x):
    total = 0
    for i in range(500000):
        total += np.sqrt(x * i)
    return total

values = df['Number of Trips 10-25'].head(20).tolist()

#now we run sequencial execution
start = time.time()

seq_results = [heavy_computation(v) for v in values]

seq_time = time.time() - start
seq_time

#and then parallel execution
start = time.time()

with Pool(cpu_count()) as p:
    par_results = p.map(heavy_computation, values)

par_time = time.time() - start
par_time

#to compare the output times for both executions we do
times = pd.DataFrame({
    'Method': ['Sequential', 'Parallel'],
    'Time (seconds)': [seq_time, par_time]
})

times

#and then save the table

times.to_csv("processing_times.csv", index=False)

#to better visualise this comparison, we will use a bar chart
plt.figure(figsize=(10,7))
plt.bar(['Sequential', 'Parallel'], [seq_time, par_time], color=['black', 'yellow'])
plt.ylabel("Time (seconds)")
plt.title("Sequential vs Parallel Processing Time")

plt.savefig("parallel_vs_sequential_times.png", dpi=300)
plt.show()

